
op: "AdaptivePolyGraphOp"

adaptive: true

network:
  kind: random
  type: erdos_renyi
  size: 100
  random:
    probability: 0.1
    tries: 10
    seed: 42
  directed: false
  selfloop: false

simulation:
  steps: 100
  repeats: 1
  adaptive: true
  logging: true
  logging_interval: 1
  results: "/content/gdrive/MyDrive/Bootcamp-results/adaptive-results/test/"

device: cpu
init:
  type: gaussian
  mean: 0.0
  std: 0.5

belief_update_rule: sigma_AD
alpha: 2.0
K: 2.0
dt: 0.01

adaptation_rule: homophily_based_AD
adaptation_params:
  gamma: 0.0
  m: 10

adaptive_logging: true
adaptive_logging_interval: 1 
adaptive_logging_dir: /content/gdrive/MyDrive/Bootcamp-results/adaptive-results/test/"

# Activities section added here
# activities:
  # type: gaussian  # Options: gaussian, exponential, powerlaw
  # params:
  #   mean: 0
  #   std: 2

activities:
  type: powerlaw  # Options: gaussian, exponential, powerlaw
  params:
    powerlaw_alpha: 2.1

